services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - '3000:3000'
  mongo:
    image: mongo
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run test
    profiles:
      - test